# Generated by Django 5.0.6 on 2024-06-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_owner_userbookrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Awful'), (2, 'Bad'), (3, 'Ok'), (4, 'Fine'), (5, 'Well')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
